//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empolyee_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpenseReport
    {
        public int Id { get; set; }
        public string Names { get; set; }
        public string ExpenseType { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Department { get; set; }
    }
}
